# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('country', models.CharField(default=b'Trinidad', max_length=25)),
            ],
        ),
    ]
