# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 03:12
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
